### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by ghost** [arsium/SysCallLib#1]
Good morning
May I know how you do the program update?
I would like to know the answer to the questions
Is it possible to update the program without a server?
I would also like to know how it is possible to do this in visual basic?

Thank you in advance for your response

The fact is that I noticed the update module on your remote access tool, I myself am not interested in remote access tools, it's just that your profile has quite a lot of interesting modules

**Comment by arsium** [comment]
> Good morning May I know how you do the program update? I would like to know the answer to the questions Is it possible to update the program without a server? I would also like to know how it is possible to do this in visual basic?
> 
> Thank you in advance for your response
> 
> The fact is that I noticed the update module on your remote access tool, I myself am not interested in remote access tools, it's just that your profile has quite a lot of interesting modules

Hello Sir,
I really did not understand your different questions  😅
What do you mean by "May I know how you do the program update?", "Is it possible to update the program without a server?" and to do what in visual basic ?

**Comment by ghost** [comment]
I will try to express my questions more agreement
I have a program written by me on vb.net
I'm going to sell it soon, but the fact is that when an update arrives, I may not count all my buyers, so I create a secret chat with people who bought my product
I'm going to send the update in the form of an exe file, by clicking on which the program received an available update 

And now I would like to know how it is possible to do this, since your remote access tool has such a file, but it is written in c#, and in this situation it is also not a very pleasant language for me, if you can help me with this I will be grateful to you

**Comment by arsium** [comment]
Ok ok I will explain how to do that.

So let's start : 

You have 2 exes files : 

* your main program
* your "updater"

The updater should be coded to call an API (whatever you want I used GitHub API for example) that gives information about updates (changelogs, version...) and a direct link to your new version of main program . When run, the updater has to check main program version with online update API. If version is older than API, the updater downloads the new main program from direct link and overwrite it locally.😃

If you need to convert VB/C#, you could use : https://www.tangiblesoftwaresolutions.com/product_details/csharp-to-vb-converter.html or https://converter.telerik.com/

**Comment by ghost** [comment]
Oh thank you my friend
I will write to this repository in about 2-3 days, I need time to code it
I just needed to understand the essence of a software update

I'll let you know if I can make it
After all, any programmer makes the program to the end, even with errors

**Comment by ghost** [comment]
* After sitting for about a week, I finally figured out how to do it
* I had big problems updating via the  github api so I just decided that I would do something similar to my host and in the end I managed to update without errors
* Thank you friend, you save me every time

**Comment by arsium** [comment]
> * After sitting for about a week, I finally figured out how to do it
> * I had big problems updating via the  github api so I just decided that I would do something similar to my host and in the end I managed to update without errors
> * Thank you friend, you save me every time

You're welcome ! Happy that you did figure out how it works :)

**Comment by ghost** [comment]
The fact is that I have more work with applications for android
I wanted to know how to do such updates, but still I would not like to dwell on the fact that something is difficult for me, I will try to update via api to know what could be the way out for me in case of a breakdown of my server or host locale
